#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#import requests
import os



print(os.environ.get('GITHUB_HEAD_REF', '---'))
#  const client = new github.GitHub(process.env.GITHUB_TOKEN;
print(os.environ.get('GITHUB_REF', '---')) #refs/pull/5190/merge
print(os.environ.get('GITHUB_REPOSITORY', '---'))


json_stuff = requests.get(url.format(repo, ref), headers={
    'Accept': 'application/vnd.github.groot-preview+json',
    'Authorization': 'token {}'.format(os.environ['GITHUB_TOKEN'])
}).json()
