extends:
  - openlayers
  - plugin:@typescript-eslint/recommended
env:
  jquery: true
parserOptions:
  ecmaVersion: 2017
  project: ./tsconfig-eslint.json
plugins:
  - copyright
rules:
  no-console: 0
  comma-dangle: 0
  import/no-unresolved: 0
  valid-jsdoc: 0
  no-unused-vars: error
  prettier/prettier:
    - error
    - singleQuote: true
      bracketSpacing: false
      quoteProps: preserve
      printWidth: 110
  sort-imports-es6-autofix/sort-imports-es6: 0
  copyright/copyright: error
  '@typescript-eslint/indent': 0
  '@typescript-eslint/no-unused-vars': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-unnecessary-type-assertion':
    - error
  '@typescript-eslint/no-for-in-array':
    - error
  '@typescript-eslint/no-this-alias':
    - error
  '@typescript-eslint/no-useless-constructor':
    - error
  '@typescript-eslint/prefer-for-of':
    - error
  '@typescript-eslint/prefer-includes':
    - error
  '@typescript-eslint/prefer-string-starts-ends-with':
    - error
  '@typescript-eslint/restrict-plus-operands':
    - error
  '@typescript-eslint/ban-ts-ignore': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/explicit-module-boundary-types': 0

settings:
  jsdoc:
    preferredTypes:
      'Array<>': '[]'
