extends:
- openlayers
env:
    jquery: true
    jasmine: true
parserOptions:
  ecmaVersion: 2017
plugins:
  - '@openlayers'
rules:
  no-console: 0
  comma-dangle: 0
  import/no-unresolved: 0
  valid-jsdoc: 0
  '@openlayers/valid-tsdoc':
    - error
    - requireReturn: false
  max-len:
    - error
    - code: 110
globals:
    angular: false
    Cesium: false
    google: false
    Bloodhound: false
    DateFormatter: false
    localforage: false
