extends:
- openlayers
- .eslintrc-es6.yaml
env:
    jquery: true
    jasmine: true
rules:
    no-console: 0
    comma-dangle: 0
globals:
    angular: false
    Cesium: false
    goog: false
    google: false
    d3: false
    Bloodhound: false
    ol: false
    olcs: false
    proj4: false
    saveAs: false
    ngeo: false
    gmf: false
    app: false
    gmfapp: false
    inject: false
    jsts: false
    moment: false
