extends:
- openlayers
- .eslintrc-es6.yaml
env:
    jquery: true
    jasmine: true
rules:
    no-console: 0
    comma-dangle: 0
globals:
    angular: false
    Cesium: false
    google: false
    Bloodhound: false
    DateFormatter: false
