ci:
  skip:
    - copyright

repos:
  - repo: https://github.com/sbrunner/pre-commit-hooks
    rev: 0.5.0
    hooks:
      - id: copyright
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.8 # npm
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: (^contribs/gmf/test/spec/data/themescapabilities\.js$|^contribs/gmf/test/spec/data/themes\.js$|^buildtools/asitvd.capabilities\.xml$|^examples/measure\.js$|^src/bootstrap-custom\.css\.map$)
        args:
          - --ignore-words=spell-ignore-words.txt
