# https://pre-commit.com/hooks.html

exclude: ^src/bootstrap-custom\.css\.map$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        exclude: ^private.key$
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^tsconfig.json$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |-
          (?x)^(
            contribs/gmf/test/spec/data/themescapabilities\.js
            |contribs/gmf/test/spec/data/themes\.js
            |buildtools/asitvd.capabilities\.xml
            |examples/measure\.js
            |src/bootstrap-custom\.css\.map
            |buildtools/sgx\.capabilities\.xml
            |package-lock\.json
          )$
        args:
          - --ignore-words=.github/spell-ignore-words.txt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.2 # npm
          - prettier-plugin-sh@0.14.0 # npm
          - prettier-plugin-toml@2.0.1 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
        exclude: |-
          (?x)^(
            \.npmignore
            |\.gitignore
            |\.prettierignore
            |examples/svg\.html
          )$
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        args:
          - -disable-indentation
          - -disable-max-line-length
        exclude: |-
          (?x)^(
            secrets\.tar\.enc
          )$
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
      - id: check-renovate
        additional_dependencies:
          - pyjson5==1.6.8 # pypi
      - id: check-github-actions
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
        exclude: |-
          (?x)^(
            private.key
            |contribs/gmf/apps/desktop_alt/index.html.ejs
            |examples/googlestreetview.html
            |examples/mapillarystreetview.js
          )$
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: v8.31.0
    #   hooks:
    #     - id: eslint
    #       additional_dependencies:
    #         - '@typescript-eslint/eslint-plugin@5.48.0'
    #         - '@typescript-eslint/parser@5.48.0'
    #         - eslint@8.31.0
    #         - eslint-plugin-jsdoc@39.6.4
    #         - eslint-plugin-lit@1.7.2
    #         - eslint-plugin-wc@1.4.0
  - repo: https://github.com/sbrunner/hooks
    rev: 1.1.2
    hooks:
      - id: copyright
      - id: workflows-require-timeout
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.3.2
    hooks:
      - id: jsonschema-validator
        files: ^ci/config\.yaml$
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.142.7
    hooks:
      - id: renovate-config-validator
