extends:
  - eslint:recommended

plugins:
  - copyright

parserOptions:
  sourceType: module
  ecmaVersion: 2020

env:
  es6: true
  node: true

rules:
  no-multi-asterisks: off
  no-prototype-builtins: warn
  no-case-declarations: warn
  no-eq-null: error
  no-multi-assign: error
  no-negated-in-lhs: error
  no-use-before-define:
    - error
    - nofunc
  no-var: error
  copyright/copyright: error
