#!/usr/bin/env python3

# The MIT License (MIT)
#
# Copyright (c) Camptocamp SA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import argparse
import os
import shutil
import subprocess
import sys
import tempfile


def main():
    """
    Compare similarity of tow images, we can use an optional mash file.
    On error a diff image is generated.

    Usage: check-example <generated image> <reference image>

    ex:
    Generated image (should ends with .html.png): .build/examples-hosted/simple.html.png
    Reference image (should ends with -ref.png): examples/simple-ref.png
    =>
    Optional mask image (name from Reference image): examples/simple-mask.png
    Generate diff image (name from Generated image): .build/examples-hosted/simple-diff.png
    """
    parser = argparse.ArgumentParser(description=main.__doc__)
    parser.add_argument("--generate", action="store_true", help="Regenerate the ref image")
    parser.add_argument("current", help="The current image")
    parser.add_argument("ref", help="The reference image")
    args = parser.parse_args()

    current = args.current
    ref = args.ref
    mask = ref.replace("-ref", "-mask")
    diff = current.replace(".html.png", "-diff.png")
    old_ref = ref

    if os.path.exists(mask):
        print("Apply mask: " + mask)
        old_current = current
        current = tempfile.NamedTemporaryFile(suffix="-current.png").name
        ref = tempfile.NamedTemporaryFile(suffix="-ref.png").name
        subprocess.run(["gm", "composite", "-compose", "Multiply", old_current, mask, current], check=True)
        subprocess.run(["gm", "composite", "-compose", "Multiply", old_ref, mask, ref], check=True)

    if args.generate and "/error-" not in ref:
        shutil.copyfile(current, old_ref)
        shutil.copyfile(current, ref)
        sys.exit(0)
    result = subprocess.run(
        [
            "gm",
            "compare",
            "-metric",
            "RMSE",
            "-highlight-style",
            "assign",
            current,
            old_ref,
            "-file",
            diff,
        ],
        check=True,
        stdout=subprocess.PIPE,
    )
    result = float(result.stdout.decode().splitlines()[-1].split()[1])
    if os.environ.get("REGENERATE_EXAMPLES") == "true":
        if result > 0:
            shutil.copyfile(current, old_ref)
            print(f"::error file={old_ref}:: Regenerate the ref image: {old_ref}")
        else:
            os.remove(old_ref)
    else:
        if result > 0.01:
            print(f"{result} > 0.01 => {diff}")
            sys.exit(1)


if __name__ == "__main__":
    main()
