#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2018-2019, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

import glob
import re

all_required_js = set()
IMPORT_FROM = re.compile(r"^import +.* +from +'(.*)';$")
ONLY_IMPORT = re.compile(r"^import +'(.*)';$")
for pathname in ("src/**/*.js", "contribs/gmf/src/**/*.js"):
    for filename in glob.glob(pathname, recursive=True):
        with open(filename) as js:
            js = js.read().split("\n")
            js = [e for e in js if "import" in e]
            for line in js:
                match = IMPORT_FROM.match(line)
                if match:
                    all_required_js.add(match.group(1))
                else:
                    match = ONLY_IMPORT.match(line)
                    if match:
                        all_required_js.add(match.group(1))

all_required_js = {a.strip() for a in all_required_js}
all_required_js = {a for a in all_required_js if not a.startswith("./")}
all_required_js = {a for a in all_required_js if not a.startswith("ngeo/")}
all_required_js = {a for a in all_required_js if not a.startswith("gmf/")}
all_required_js = {a for a in all_required_js if not a.startswith("goog/")}
all_required_js = {a for a in all_required_js if not a.startswith("olcs/")}
all_required_js = {a for a in all_required_js if not a.startswith("jsts/")}
all_required_js = {a for a in all_required_js if not a.startswith("mapillary-js/")}
all_required_js = {
    a for a in all_required_js if a not in ("corejs-typeahead", "angular-float-thead", "moment")
}
all_required_js = {a for a in all_required_js if not a.endswith(".css")}
for js in sorted(all_required_js):
    print("require('{}')".format(js))
