#!/usr/bin/python

import sys
import subprocess



if len(sys.argv) != 3 or sys.argv[1] in ('-h', '--help'):
    print("Usage: {} GREP SED".format(sys.argv[0]))
    print("")
    print("GREP: The git grep expression.")
    print("SED: The sed expression.")
    exit(0)

try:
    for file_name in subprocess.check_output(["git", "grep", "-i", "-l", "--full-name", "--", sys.argv[1]]).strip().split("\n"):
        subprocess.check_call(["sed", "-i", "-e", sys.argv[2], file_name])
except subprocess.CalledProcessError as e:
    print(e)
    exit(1)
