#!/usr/bin/env python3

# The MIT License (MIT)
#
# Copyright (c) Camptocamp SA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import argparse
import glob
import os
import shutil
import subprocess
import sys
import tempfile


def mask_ref(mask):
    ref = mask.replace("-mask", "-ref")
    print(ref)
    subprocess.run(["gm", "composite", "-compose", "Multiply", ref, mask, ref], check=True)


def main():
    """
    Mask the reference image with the mask image.
    """
    parser = argparse.ArgumentParser("Mask the reference image with the mask image.")
    parser.parse_args()

    for file in glob.glob("examples/*-mask.png"):
        mask_ref(file)
    for file in glob.glob("contribs/gmf/examples/*-mask.png"):
        mask_ref(file)
    for file in glob.glob("contribs/gmf/apps/*-mask.png"):
        mask_ref(file)


if __name__ == "__main__":
    main()
