#!/bin/bash -e

PACKAGE_VERSION=$(buildtools/get-version version)
echo "Trying to publish tag ${GITHUB_REF} from package ${PACKAGE_VERSION} on ${GITHUB_REPOSITORY}"

if [[ $@ =~ "--dry-run" ]]; then RUN="echo "; fi

if [ "${GITHUB_REPOSITORY}" = "camptocamp/ngeo" ]; then
    if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
        GIT_TAG=$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')
        echo "The tag ${GIT_TAG} should be published to npm"
        if [[ ${GIT_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+-[a-z]+\.[0-9]+$ ]]; then
            echo "This is a regular version (not a dev version)"
            export TAG="--tag version-$(echo ${GIT_TAG} | awk -F[.-] '{print $4}')"
        else
            echo "This is not a regular version"
        fi
        if [ "${PACKAGE_VERSION}" = "${GIT_TAG}" ]; then
            $RUN npm publish --tag=version-${MAIN_BRANCH} ${TAG}
        else
            echo "Skipping publication, the Git tag and package version differ"
        fi
    else
        if [ "${GITHUB_REF}" = "refs/heads/${MAIN_BRANCH}" ]; then
            GIT_BRANCH=$(echo ${GITHUB_REF} | sed 's|refs/heads/||g')
            echo "Publish daily version"
            $RUN npm install --no-save fluid-publish
            if [ "${MAIN_BRANCH}" = "master" ]; then
                $RUN node_modules/.bin/fluid-publish devTag="latest"
            else
                $RUN node_modules/.bin/fluid-publish devTag="version-${MAIN_BRANCH}-latest"
            fi
        fi
    fi
fi
