#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re
import sys

if len(os.environ.get("GITHUB_REF", "")) == 0:
    sys.exit(0)

with open("package.json") as package_json_file:
    package_json = json.loads(package_json_file.read())

version = os.environ["GITHUB_REF"].split("/")
if len(version) != 3 or version[1] != "tags":
    sys.exit(0)
version = version[2]

match_dev = re.match(r"([0-9]+\.[0-9]+\.[0-9]+)-([a-z]+)\.([0-9]+)", version)
if match_dev is None:
    if package_json["version"] == version:
        sys.exit(0)
    else:
        sys.exit(1)

package_json["version"] = version

with open("package.json", "w") as package_json_file:
    package_json_file.write(json.dumps(package_json, sort_keys=True, indent=2))
