#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
import re

if not os.environ["GITHUB_REF"].startswith("refs/tags"):
    exit(0)

with open("package.json") as package_json_file:
    package_json = json.loads(package_json_file.read())

version = os.environ["GITHUB_REF"].split("/")[2]
match_dev = re.match(r"([0-9]+\.[0-9]+\.[0-9]+)-([a-z]+)\.([0-9]+)", version)
if match_dev is None:
    if package_json["version"] == version:
        exit(0)
    else:
        exit(1)

package_json["version"] = version

with open("package.json", "w") as package_json_file:
    package_json_file.write(json.dumps(package_json, sort_keys=True, indent=2))
