#!/bin/bash -ex

if [ "${DO_EXAMPLES_DEPLOY}-${IS_PR}" = TRUE-TRUE ]; then
  if [ "${TRAVIS_PULL_REQUEST_SLUG}" != camptocamp/ngeo ]; then
    if [ "${EXAMPLES_NGEO}" == TRUE ]; then
      make examples-hosted-ngeo
    fi
    if [ "${EXAMPLES_GMF}" == TRUE ]; then
      make examples-hosted-gmf
    fi
    if [ "${APPS_GMF}" == TRUE ]; then
      make examples-hosted-apps
    fi
    if [ "${API}" == TRUE ]; then
      make .build/apidoc
    fi
  fi
fi
