#!/bin/bash -ex

function jscodeshift {
    node_modules/.bin/jscodeshift $* | tee /tmp/jscodeshift.log
    grep --quiet '^0 errors$' /tmp/jscodeshift.log
    rm /tmp/jscodeshift.log
}

node node_modules/googshift/filename-case-from-module.js src '*.js'
node node_modules/googshift/filename-case-from-module.js contribs/gmf/src '*.js'
node node_modules/googshift/filename-case-from-module.js contribs/gmf/apps '*.js'
JSCS_ARGS="--non-default-import=ol,ol/proj,ol/proj/proj4,ol/dom,ol/array,ol/math,ol/extent,ol/easing,ol/color,ol/obj,ol/uri,ol/functions,ol/Sphere --package=ngeo,ol"
jscodeshift --transform=node_modules/googshift/transforms/goog_provide_to_goog_module.js $JSCS_ARGS src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test contribs/gmf/apps
jscodeshift --transform=node_modules/googshift/transforms/goog_module_to_es6_module.js $JSCS_ARGS --absolute-module=true src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test
jscodeshift --transform=node_modules/googshift/transforms/goog_module_to_es6_module.js $JSCS_ARGS contribs/gmf/apps
sed -i '/^if/d' src/proj/somerc.js src/proj/lcc.js src/proj/utm.js
sed -i '/^  ol/d' src/proj/somerc.js src/proj/lcc.js src/proj/utm.js
sed -i '/^}$/d' src/proj/somerc.js src/proj/lcc.js src/proj/utm.js
git add -A  # To be removed when we use the new OpenLayers version
buildtools/git-grep-sed 'Sphere' 's|ol/Sphere|ol/sphere|g'
find -name node_modules -prune -or -name '*.js' -print | xargs sed -i 's|^// webpack: ||g'
node_modules/.bin/eslint --fix src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test contribs/gmf/apps || true
mv karma-conf{-webpack,}.js
mv src/{ngeo,index}.js
mv contribs/gmf/src/{gmf,index}.js
mv src/goog.asserts.js{_,}
mv src/goog.asserts.prod.js{_,}
buildtools/git-grep-sed 'gmf/test/data/' 's/\<gmfTestDataThemes\>/themes/g'
buildtools/git-grep-sed 'gmf/test/data/' 's/\<gmfTestDataPrintcapabilities\>/printCapabilities/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputFuel\>/msGMLOutputFuel/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputBusStop\>/gmlResponseBusStop/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputBusStopAndInformation\>/gmlResponseBusStopAndInformation/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputInformationWfs\>/gmlResponseInformationWfs/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputBusStopWfs\>/gmlResponseBusStopWfs/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataMsGMLOutputInformationHitsWfs\>/gmlResponseInformationHitsWfs/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataWmtsCapabilities\>/wmtsCapabilities/g'
buildtools/git-grep-sed 'ngeo/test/data/' 's/\<ngeoTestDataGeoAdminLocationSearch\>/geoAdminLocationSearch/g'
#sed '/ngeo:/d' -i .eslintrc.yaml
#sed '/gmf:/d' -i .eslintrc.yaml
#sed '/ol:/d' -i .eslintrc.yaml
sed '/olcs:/d' -i .eslintrc.yaml
#sed '/app:/d' -i .eslintrc.yaml
#sed '/gmfapp:/d' -i .eslintrc.yaml
sed '/proj4:/d' -i .eslintrc.yaml
git reset --mixed
set +x

echo ------------------------
echo Clean used scripts with:
echo '  git rm buildtools/git-grep-sed buildtools/webpack-migration'
echo
echo 'If your repository was completely clean (git clean --force -d) you can do the commit with:'
echo '  git add -A'
echo '  git commit -m "Apply the webpack migration"'
