#!/bin/bash -ex

function jscodeshift {
    node_modules/.bin/jscodeshift $* | tee /tmp/jscodeshift.log
    grep --quiet '^0 errors$' /tmp/jscodeshift.log
    rm /tmp/jscodeshift.log
}

rm -f src/jstsexports.js
rm -rf third-party/
rm -f examples/default.js
rm -f contribs/gmf/apps/default.js
rm -f contribs/gmf/examples/default.js
rm -f buildtools/templatecache.mako.js
rm -f src/ngeo.js
node node_modules/googshift/filename-case-from-module.js src '*.js'
node node_modules/googshift/filename-case-from-module.js contribs/gmf/src '*.js'
node node_modules/googshift/filename-case-from-module.js contribs/gmf/apps '*.js'
JSCS_ARGS="--non-default-import=ol,ol/size,ol/string,ol/has,ol/coordinate,ol/events,ol/events/condition,ol/xml,ol/proj,ol/proj/proj4,ol/dom,ol/array,ol/math,ol/extent,ol/easing,ol/color,ol/obj,ol/uri,ol/functions,ol/Sphere,ol/format/Feature,ol/format/filter,ol/interaction --package=ngeo,ol,gmf"
jscodeshift --transform=node_modules/googshift/transforms/goog_provide_to_goog_module.js $JSCS_ARGS src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test contribs/gmf/apps
jscodeshift --transform=node_modules/googshift/transforms/goog_module_to_es6_module.js $JSCS_ARGS --absolute-module=true src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test
jscodeshift --transform=node_modules/googshift/transforms/goog_module_to_es6_module.js $JSCS_ARGS contribs/gmf/apps
git add -A  # To be removed when we use the new OpenLayers version
buildtools/git-grep-sed 'Sphere' 's|ol/Sphere|ol/sphere|g'
buildtools/git-grep-sed webpack 's|// webpack: ||g'
buildtools/git-grep-sed webpack '/nowebpack$/d'
node_modules/.bin/eslint --fix src contribs/gmf/src examples contribs/gmf/examples test contribs/gmf/test contribs/gmf/apps || true
mv karma-conf{-webpack,}.js
mv contribs/gmf/src/{gmf,index}.js
mv src/goog.asserts.js{_,}
mv src/goog.asserts.prod.js{_,}
sed '/ngeo:/d' -i .eslintrc.yaml
sed '/gmf:/d' -i .eslintrc.yaml
sed '/ol:/d' -i .eslintrc.yaml
sed '/olcs:/d' -i .eslintrc.yaml
sed '/app:/d' -i .eslintrc.yaml
sed '/gmfapp:/d' -i .eslintrc.yaml
sed '/proj4:/d' -i .eslintrc.yaml
sed '/d3:/d' -i .eslintrc.yaml
sed '/goog:/d' -i .eslintrc.yaml
sed '/jsts:/d' -i .eslintrc.yaml
sed '/moment:/d' -i .eslintrc.yaml
sed '/saveAs:/d' -i .eslintrc.yaml
git reset --mixed
set +x

echo ------------------------
echo Clean used scripts with:
echo '  git rm buildtools/git-grep-sed buildtools/webpack-migration contribs/gmf/apps-webpack buildtools/create-es6-package'
echo
echo Fix alone comment in contribs/gmf/src/gmf.js
echo
echo 'If your repository was completely clean (git clean --force -d) you can do the commit with:'
echo '  git add -A'
echo '  git commit -m "Apply the webpack migration"'
