plugins:
  - googshift
rules:
  googshift/no-duplicate-requires: error

  googshift/no-missing-requires:
    - error
    - prefixes: [gmf, ngeo, ol]

  googshift/no-unused-requires: warn

  googshift/one-provide-or-module:
    - error
    - entryPoints: [ngeo]
      root: src

  googshift/requires-first: error

  googshift/valid-provide-and-module:
    - warn
    - entryPoints: [ngeo]
      root: src/module
      replace: ../../contribs/gmf/src|gmf

  googshift/valid-requires: error
