plugins:
  - googshift

rules:
  googshift/no-duplicate-requires: error

  googshift/no-missing-requires:
    - warn
    - prefixes: [gmf, ngeo, ol]

  googshift/no-unused-requires: warn

  googshift/one-provide-or-module:
    - warn
    - entryPoints: [gmf]
      root: src

  googshift/requires-first: error

  googshift/valid-provide-and-module:
    - warn
    - entryPoints: [gmfapp, ngeo]
      root: fakeroot
      replace: ../contribs/gmf/examples|gmfapp

  googshift/valid-requires: error
