plugins:
  - googshift

rules:
  googshift/no-duplicate-requires: error

  googshift/no-missing-requires:
    - warn
    - prefixes: [ngeo, ol]

  googshift/no-unused-requires: warn

  googshift/one-provide-or-module:
    - warn
    - entryPoints: [ngeo]
      root: src

  googshift/requires-first: error

  googshift/valid-provide-and-module:
    - warn
    - entryPoints: [ngeo]
      root: src
      replace: ../examples|app

  googshift/valid-requires: error
