# yaml-language-server: $schema=https://raw.githubusercontent.com/sbrunner/applications-download/master/applications_download/applications-schema.json

transifex/cli:
  description: Transifex CLI
  type: tar
  get-file-name: tx-linux-amd64.tar.gz
  tar-file-name: tx
  to-file-name: tx
  finish-commands:
    - - chmod
      - +x
      - tx
    - - tx
      - --version
